VerifiedInc/VerifiedInc.github.io

.github/workflows/deploy.yaml
.github/workflows/preview.yaml
README.md
package-lock.json
package.json

Setup a preview docs deployment to deploy to the `preview` branch triggered by git tag pushes in the format `preview-v*.*.*` where the *'s are semvar notation. It deploys via Netlfy to https://resilient-capybara-2fa074.netlify.app/.
Also updated to use latest node version 18.15.0
- readme
- actions
- deployed successfully

[Deployment] preview setup

---

docs/1-click-or-free-use-case.mdx
docs/about-unum-id.mdx
docs/acceptance-guide.mdx
docs/api-overview.mdx
docs/faq.mdx

Updated based on Aidan's feedback. https://docs.google.com/document/d/1Lkf45KpHxBGOvppz7zB5UKeNqewtpMo15QfEbZClewg/edit#
- fixes
- demos
- deployed via preview tag to https://resilient-capybara-2fa074.netlify.app/

[Acceptor] guide updated. Some typo edits.

---

docs/1-click-or-free-use-case.mdx
docs/acceptance-guide.mdx

[Ticket](https://trello.com/c/lepQAsW0/5105-update-hasmatchingcredentials-docs-to-reflect-that-the-matching-uids-are-part-of-the-request-url-in-the-response)
Docs updated to show the uids included the hasMatchingCredentials url response.
- example responses updated
- n/a

[hasMatchingCredentials] respone body url updated to include the matching email or phone

---

docs/api-overview.mdx

[ticket](https://trello.com/c/wKcTwVsY/5196-add-sharedcredentialsuuid-url-param-name-and-example-to-docs)
Updated api section with more info on the `redirectUrl` and `sharedCredentialUuid`
- api page updated
- locally

[Api] updated with more detailed sharedCredentialUuid info

---

docs/acceptance-guide.mdx
docs/api-overview.mdx
docs/issuance-guide.mdx

[Ticket](https://trello.com/c/1MAyJNLk/5257-document-dummy-user)
Added mention of the dummy user.
- mention in issuance guide 
- mention in acceptance guide 
- mention in api page
- locally
- deployed to preview https://resilient-capybara-2fa074.netlify.app/

[Dummy User] mention.

---

docs/api-overview.mdx
docs/issuance-guide.mdx

Documentation on the new breaking change in regard to the issuance response body. Also, a new section in the issuance guide related to partner issuance. 
- api update
- issuance guide update
- locally

[Partner Issuance] documentation added. Breaking issue credentials response body.

---

docs/api-overview.mdx
docs/issuance-guide.mdx

This reverts commit 0caa0db07152f4fba167ab17c8ee68ab84a9d93c.
Reverting this and then doing a new release so this is not public facing until the functionality is in Sandbox.

Revert "[Partner Issuance] documentation added. Breaking issue credentials response body. (#76)"

---

docs/schema.mdx

Schema section explaining the relevance of JSON-LD removed as it related to DIDs and VC.
- removed mention of DIDs and VCs

[Schema] section explaining the relevance of JSON-LD removed as it related to DIDs and VC.

---

docs/api-overview.mdx
docs/issuance-guide.mdx

This reverts commit 8f9eb2edfcebc553fb37bd00abc05b55fea5f793.
Adding back in the partner issuance docs that have already been reviewed and merged. Time sensitive (hotfix) because core-service has just been released to sandbox. 
-revert a revert

Revert "Revert "[Partner Issuance] documentation added. Breaking issue credentials response body. (#76)" (#77)"

---

docs/faq.mdx
docs/issuance-guide.mdx
docusaurus.config.js

Updated the Partner Issuance wording for clarity. Provided an example response. 
Fixed the footer
Fixed the faq path
- [Partner Issuance]
- footer
- faq path refactor
- locally

[Footer] fixed. Partner Issuance example added. 

---

docs/api-overview.mdx

API section updated with credential patch information.
- credential patch api section
- removed the email and phone ids from the credential response body examples in preparation to remove them in the core service
- locally

[API] credential patch documentation.

---

docs/acceptance-guide.mdx
docs/issuance-guide.mdx

Added headers to the implementation guide's implementation section so can be directly linkable. 
- [Acceptance Guide] added headers for each step so they are directly linkable.
- [Issuance Guide] links
- locally
- preview https://resilient-capybara-2fa074.netlify.app/acceptance-guide/#implementation

[Guides] added linkable implementation step headers.

---

docs/acceptance-guide.mdx

Implementing Liam's suggestions that were not committed in https://github.com/UnumID/UnumID.github.io/pull/88
- passive to active voice
- local

suggestions

---

docs/acceptance-guide.mdx

Mentioning the need to pre-define their redirect url with us.
- mentioning the need to pre-define their redirect url with us.
- local

[Acceptance Guide] partner acceptance menioning need to pre-define the redirect url.

---

docs/api-overview.mdx
docs/issuance-guide.mdx

Added the get credential api request documentation. Update `partnerUrl` to `url` in /credentials response. Added a tiny bit of info on the credential request check conditional for the `url` being present. 
- [API] get credential by id added. Also update /credentials response to contian url not partnerUrl.
- issue
- credsUrl
n/a

[API] get credential endpoint documented. Credentials url conditions mentioned.

---

docs/issuance-guide.mdx

[suggestions] from liam

---

docs/acceptance-guide.mdx

[acceptance]: fix sandbox url

---

.gitignore
docs/about-unum-id.mdx
docs/hooli-partner-demo.mdx
docusaurus.config.js
sidebars.js

[Ticket](https://trello.com/c/IRaclA1c/5452-build-new-demo-showing-partner-issuance-from-hooli-to-kredita)
Adds hooli partner demo page and overview information that points to the related page.
- add new page
- add new sidebar demo option
- add overview information
Tested locally the pages.

chore: Add hooli partner demo page

---

docs/hooli-partner-demo.mdx

[Ticket](https://trello.com/c/IRaclA1c/5452-build-new-demo-showing-partner-issuance-from-hooli-to-kredita)
Adds hooli partner demo page and overview information that points to the related page. Also improved the readability requested in https://github.com/UnumID/UnumID.github.io/pull/99
Add more readable hooli partner demo page texts.

refactor(partner demo) Add more readability

---

.prettierignore
.prettierrc
docs/schema.mdx
package-lock.json
package.json
src/components/Schemas/Schemas.jsx
src/components/Schemas/Schemas.module.css
src/components/Schemas/components/SchemaDetails.jsx
src/components/Schemas/components/style.module.css
src/css/custom.css
src/mappers/mapSchemaDto.ts
src/services/schemaResolver.js
src/utils.js

[Ticket](https://trello.com/c/sp38fMZi/5475-load-and-display-json-schemas-in-the-docs)
Now the docs has the new section of schema library, which you can search and see more details about it in a more clear and easy way, also it allows you to copy to clipboard the json schema.
https://github.com/UnumID/UnumID.github.io/assets/13892132/1f239f4e-21e3-48cc-ab28-4498e40fad34
Add new section to data schemas page.

Feat: Add schema library section

---

docs/acceptance-guide.mdx
docs/issuance-guide.mdx

Bumping time to implement to be more realistic. 
- acceptance guide time to implement
- issuer guide time to implement
- n/a

[guides] time to implement estimate updated.

---

docs/acceptance-guide.mdx
docs/api-overview.mdx
docs/issuance-guide.mdx
docs/reusables/credential-request-code-snippet.mdx
docs/schema.mdx
docs/terminology.mdx

[Ticket](https://trello.com/c/vqtb9GoJ/5808-write-docs-to-composite-credentials)
Docs for Composite Credential

feature: add docs to composite credential

---

docs/acceptance-guide.mdx
docs/api-overview.mdx

Fix mention of needing to register as a customer with zero to many brands... was language that made more sense in relation to our self-service dashboard. 
- removed customer creation mention
- removed zero brands mention
- moved the postman doc mention into #overview
- locally

[API] intro fix to drop mention of customer creation and brand count.

---

docs/acceptance-guide.mdx

[Ticket](https://trello.com/c/QSNuTJYU/5817-update-required-term-in-docs)
Update required term.
- updated term

refactor: rename term required to mandatory

---

docs/1-click-or-free-use-case.mdx
docs/acceptance-guide.mdx
docs/issuance-guide.mdx
docs/reusables/shared-credentials-body.mdx

Fixed the SSN credential data format. Also made the SharedCredentials response body example more detailed.
- fix
- shared cred response example
- locally

fix: ssn credential data formats.

---

docs/api-overview.mdx
docs/issuance-guide.mdx

[Ticket](https://trello.com/c/rpWd2trc/5871-update-credential-call-to-handle-optional-verified-param)
TrackingId added as optional param to /credentials call documented
- api 
- issuer guide
- locally

[Tracking Identifier] mention in the API and Issuance Guide.

---

docs/api-overview.mdx
docs/reusables/credential-request-code-snippet.mdx
docs/terminology.mdx
src/components/Schemas/components/SchemaDetails.jsx

[Ticket](https://trello.com/c/lNt5DhIq/5936-document-user-inputted-credentials)
This PR adds explanation to user input feature.
- updated sections
- updated schema library

feat: user input documentation

---

src/components/Schemas/components/SchemaDetails.jsx
src/utils.js

[Ticket](https://trello.com/c/IlFDlghp/6355-fix-schema-library-doc)
This PR simplifies the rendering of any data type to the schema library details component.
- updated schema details related component and modules
https://github.com/VerifiedInc/UnumID.github.io/assets/13892132/37f3944e-de6a-43b9-a9fe-bff201fe22de

refactor: render object structure correctly

---

docs/acceptance-guide.mdx

Briefly mentioning the `verified` query param so can point acceptors to the part of the docs.

[Acceptor] verified tracking parameter.

---

docs/1-click-guide.mdx
docs/about-unum-id.mdx
docs/acceptance-guide.mdx
docs/api-overview.mdx
docs/issuance-guide.mdx
docs/reusables/1-click-default-credential-request.mdx
docs/reusables/credential-usage-example-snippet.mdx
docs/reusables/shared-credentials-body-atomic-details.mdx
docs/reusables/shared-credentials-body-atomic.mdx
docusaurus.config.js
sidebars.js

Retrofit the acceptance guide for 1click
- 1 click guide
- removed the 1click or free idv use case section
- locally
- preview: https://resilient-capybara-2fa074.netlify.app/

[1-Click] guide added.

---

docs/1-click-guide.mdx
docs/acceptance-guide.mdx
docs/issuance-guide.mdx

Updating from feedback from Nick

[Guides] time to implement inflated.

---

api/specs/api.json
docs/1-click-signup.mdx
docs/about-unum-id.mdx
docs/api-overview.mdx
docs/demos.mdx
docs/issue-to-earn.mdx
docs/reusables/1-click-default-credential-request.mdx
docusaurus.config.js
package-lock.json
package.json
sidebars.js
src/theme/ReactLiveScope/index.js

- Revamp for 1-Click Signup
- Tweaks for 1-Click Signup
[Ticket]()

Docs Revamp for 1-Click Signup

---

docs/1-click-or-free-use-case.mdx
docs/1-click-signup.mdx
docs/api-reference.mdx
docs/demo-issue-to-earn.mdx
docs/issuance-guide.mdx
docs/issue-to-earn.mdx
docs/reusables/sandbox-testing-credentials.mdx

@liamhalemccarty, I figured it was easier just to make the changes and open a pr so you can see them all in one place.

Further documentation updates. 

---

docs/api-reference.mdx
docs/kikoff-guide.mdx
docs/reusables/sandbox-testing-credentials.mdx

Typo fixes, small changes to API Overview page

---

docs/api-reference.mdx

[Typedoc] link updated to core-types.

[Typedoc] link updated to core-types.

---

docs/api-reference.mdx
docs/kikoff-guide.mdx

Updating Kikoff guide to mention upcoming change to format of data we send them

---

docs/1-click-signup.mdx
docs/api-reference.mdx

Very rough first mention of the Non-Hosted 1click flow
- [Non-Hosted] 1click mention
- match value added

[Non-Hosted] 1click

---

docs/1-click-signup.mdx

[Non-Hosted] 1 click mention of non url in code only flow.

[Non-Hosted] 1 click mention of non url in code only flow.

---

docs/1-click-signup.mdx
docs/api-reference.mdx

[Non-Hosted] typo fixes

---

docs/1-click-signup.mdx

Adding smsBody attribute and Go Live section

Adding smsBody attribute and Go Live section

---

docs/1-click-signup.mdx
docs/api-reference.mdx
docs/kikoff-guide.mdx

1Click SMS sending alignment. Also diagram for non-hosted flow added.
- [1Click] SMS sending alignment.
- nonHostedDiagram
- locally

[1Click] SMS sending alignment. Also diagram for non-hosted flow added.

---

docs/1-click-signup.mdx
docs/kikoff-guide.mdx

SMS handling is updated in 1click and Kikoff diagrams sequence diagrams for Production.
Note: running locally the arrows in the Production tab are not showing up in the mermaid diagram. Hoping this is a quirk of running locally. Deploying this branch to preview url to test / see if there too https://resilient-capybara-2fa074.netlify.app/
- 1 click sequence diagram dev / prod tabs added
- kikoff sequence diagram dev / prod tabs added
- locally

[SMS] 1click diagrams updated with sms production flow.

---

docs/api-reference.mdx

API docs for the 1-click/trusted flow.

[API] 1-click/trusted added.

---

README.md
docusaurus.config.js

[Search] indexing enabled for base page with lunr settings

[Search] indexing enabled for base page.

---

docs/api-reference.mdx

[1click] default verification method is only_code

[1click] default verification method is only_code

---

docs/1-click-signup.mdx

fix: typo in 1click guide

---

docs/1-click-signup.mdx

[1Click] redirectUrl example updated to use new signin path

[1Click] redirectUrl example updated to use new signin path

---

docs/hidden/1-click-or-free-use-case.mdx
docs/hidden/issuance-guide.mdx
docs/reusables/atomic-credential-example.mdx
docs/reusables/composite-credential-example.mdx
docs/schema.mdx

[Schema] resolver url fixed

---

docusaurus.config.js
package-lock.json
package.json
versioned_docs/version-2/reusables/credential-request-table-shared.mdx
versioned_docs/version-2/reusables/development-work-admonition.mdx
versioned_docs/version-2/reusables/integration-type-admonition.mdx
versioned_docs/version-2/reusables/post-1-click-request-body-table-shared.mdx
versioned_docs/version-2/reusables/post-1-click-response-body-table-identity.mdx
versioned_docs/version-2/reusables/post-1-click-response-body-table-uuid.mdx
versioned_docs/version-2/reusables/prompt-user-to-confirm-their-data.mdx
versioned_docs/version-2/reusables/send-sms-to-user.mdx
versioned_docs/version-2/reusables/use-your-own-phone-number-admonition.mdx

- Making v2 the default and putting v1 on /v1 path
- Removing client side redirects because for some reason they're making the build fail
- Fixing plugins issue in docusaurus.config.js
[Ticket]()

v2 as default

---

versioned_docs/version-2/reusables/update-sandbox-base-url-and-api-key.mdx

Adding info about differences between v1 and v2 for API authorization

---

versioned_docs/version-2/1-click-signup/api-reference/types.mdx
versioned_docs/version-2/reusables/1-click-entity-example.mdx
versioned_docs/version-2/reusables/credential-request-table-semi-hosted-and-non-hosted.mdx
versioned_docs/version-2/reusables/default-credential-requests-hosted.mdx

Adding documentation for multi-attribute in credential requests. 
A cleaned up PR from https://github.com/VerifiedInc/VerifiedInc.github.io/pull/188
- cred request docs and examples
- locally

Adding support for multi attribute in credential requests

---

docusaurus.config.js
versioned_docs/version-1/1-click-signup.mdx
versioned_docs/version-1/api-reference.mdx
versioned_docs/version-1/demo-issue-to-earn.mdx
versioned_docs/version-1/issue-to-earn.mdx
versioned_docs/version-1/terminology.mdx
versioned_docs/version-2/1-click-signup/api-reference/data.mdx
versioned_docs/version-2/1-click-signup/api-reference/endpoints.mdx
versioned_docs/version-2/1-click-signup/api-reference/errors.mdx
versioned_docs/version-2/1-click-signup/api-reference/types.mdx
versioned_docs/version-2/1-click-signup/integration-guide.mdx
versioned_docs/version-2/reusables/1-click-entity-example.mdx
versioned_docs/version-2/reusables/credential-request-table-semi-hosted-and-non-hosted.mdx
versioned_docs/version-2/reusables/default-credential-requests-hosted.mdx
versioned_docs/version-2/reusables/error-example-oce011.mdx
versioned_docs/version-2/reusables/error-type.mdx
versioned_docs/version-2/reusables/include-birth-date-if-possible-admonition.mdx
versioned_docs/version-2/reusables/recency-requirement-admonition.mdx
versioned_docs/version-2/reusables/when-step-is-necessary-admonition.mdx

Release docs v8.1.0 with multi support

Release docs v8.1.0 with multi support

---

versioned_docs/version-1/schema.mdx
versioned_docs/version-2/credential-schemas.mdx

[Schemas] removed references to our now closed-source schema-sdk repo. ref: https://verified-inc.slack.com/archives/CMHP6C3MY/p1727885559219289

[Schemas] removed references to our now closed-source schema-sdk repo

---

versioned_docs/version-2/1-click-signup/api-reference/data.mdx

Add info that Email isn't very reliable
[Ticket]()
https://verified-inc.slack.com/lists/TD0LFET2P/F07D02R65QC?record_id=Rec07PR5F6HBQ
local

feat: add warning about email reliability

---

versioned_docs/version-2/1-click-signup/quick-start-guide.mdx
versioned_docs/version-2/reusables/authentication-admonition.mdx

Add authentication admonition to quick start guide and create new admonition component
[Ticket](https://verified-inc.slack.com/lists/TD0LFET2P/F07D02R65QC?record_id=Rec07V25608JG)

Add authentication admonition to quick start guide

---

versioned_docs/version-2/1-click-signup/integration-guide.mdx
versioned_docs/version-2/reusables/local-testing-admonition.mdx

Add local testing admonition to integration guide
[Ticket](https://verified-inc.slack.com/lists/TD0LFET2P/F07D02R65QC?record_id=Rec07UWUGHF61)
Added reusable local testing admonition.
Called it into the integration guide.
locally

Add local testing admonition to integration guide

---

versioned_docs/version-2/1-click-signup/integration-guide.mdx

Update Non-Hosted legal language to match other integration types
[Ticket](https://verified-inc.slack.com/lists/TD0LFET2P/F07D02R65QC?record_id=Rec0811GRCG9W)
I used the same agreeToAction prop we have for the other two integration types on the non-hosted.

Update Non-Hosted legal language to match other integration types

---

src/components/AnchorOffset.jsx
versioned_docs/version-2/1-click-signup/integration-guide.mdx
versioned_docs/version-2/reusables/include-graphic-and-legal-language.mdx

Fix anchor links and create reusable components for legal language
[Ticket](https://verified-inc.slack.com/lists/TD0LFET2P/F07D02R65QC?record_id=Rec07VCB47KRP)
-  Created reusable anchor offset component
- Created a reusable component for the legal language and graphic
- Fixed the <a> navigation by adding dynamic URLs based on the integration prop
locally

Fix anchor links and create reusable component for legal language

---

versioned_docs/version-2/1-click-signup/api-reference/data.mdx

Update Fraud Signals label to indicate beta status
[Ticket]()

Update Fraud Signals label to indicate beta status

---

versioned_docs/version-2/1-click-signup/api-reference/data.mdx

Reverts VerifiedInc/VerifiedInc.github.io#214

Revert "Update Fraud Signals label to indicate beta status"

---

src/components/AnchorOffset.jsx
versioned_docs/version-2/1-click-signup/integration-guide.mdx
versioned_docs/version-2/reusables/include-graphic-and-legal-language.mdx

Fix anchor links and create reusable components for legal language
[Ticket](https://verified-inc.slack.com/lists/TD0LFET2P/F07D02R65QC?record_id=Rec07VCB47KRP)
-  Created reusable anchor offset component
- Created a reusable component for the legal language and graphic
- Fixed the <a> navigation by adding dynamic URLs based on the integration prop
locally

[Liam] Fix anchor links and create reusable component for legal language

---

versioned_docs/version-2/reusables/prompt-user-to-confirm-their-data.mdx

Update admonition for masking Social Security Numbers to enhance clarity and security guidelines
Updated admonition text and type
[Ticket](https://verified-inc.slack.com/lists/TD0LFET2P/F07D02R65QC?record_id=Rec07VCN9BJE5)
locally

[Liam] Update admonition for masking Social Security Numbers

---

versioned_docs/version-2/1-click-signup/api-reference/data.mdx

Add customer_otp verification method
[Ticket](https://verified-inc.slack.com/lists/TD0LFET2P/F07D02R65QC?record_id=Rec07R4TU6UJ2)

[Liam] Add customer_otp verification method

---

src/components/Buttons/PostmanButton.jsx
src/components/Buttons/SwaggerButton.jsx
src/css/custom.css
versioned_docs/version-2/1-click-signup/api-reference/endpoints.mdx
versioned_docs/version-2/reusables/EndpointHeader.jsx

Add swagger and postman buttons to Endpoints
[Ticket]()

Swagger postman endpoints

---

versioned_docs/version-2/1-click-signup/api-reference/data.mdx
versioned_docs/version-2/1-click-signup/api-reference/errors.mdx
versioned_docs/version-2/1-click-signup/api-reference/types.mdx

- Added risk signals metadata and reason codes to Data page, OCE017 error, and RiskSignals type
- Adjusted riskSignals info based on feedback
[Ticket]()

riskSignalsFeedback

---

versioned_docs/version-2/1-click-signup/api-reference/types.mdx

Co-authored-by: Liam Hale McCarty <37675947+liamhalemccarty@users.noreply.github.com>
Co-authored-by: Liam McCarty <liammccarty@MacBook-Pro-6.local>## Summary
Merge main into dev so we can merge dev into main
[Ticket]()

Merge main into dev so we can merge dev into main

---

versioned_docs/version-2/1-click-signup/overview.mdx

Hiding Overview page

---

versioned_docs/version-2/1-click-signup/api-reference/types.mdx

I just want to test the squash merge option to see if it has the ahead issue.
[Ticket]()

comment just to test the Squash merge option from dev to main

---

versioned_docs/version-2/1-click-signup/api-reference/types.mdx

comment just to test the Rebase merge option from dev to main
[Ticket]()

comment just to test the Rebase merge option from dev to main

---

versioned_docs/version-2/1-click-signup/api-reference/types.mdx
versioned_docs/version-2/1-click-signup/integration-guide.mdx
versioned_docs/version-2/reusables/api-keys-admonition.mdx
versioned_docs/version-2/reusables/prompt-user-to-confirm-their-data.mdx

Updated values for RiskSignals type, linked to Risk Signals on Data page, added warnings for not using API keys client side

---

versioned_docs/version-2/1-click-signup/api-reference/types.mdx
versioned_docs/version-2/1-click-signup/integration-guide.mdx
versioned_docs/version-2/reusables/api-keys-admonition.mdx
versioned_docs/version-2/reusables/prompt-user-to-confirm-their-data.mdx

Updated values for RiskSignals type, linked to Risk Signals on Data page, added warnings for not using API keys client side
[Ticket]()

RiskSignals, API Keys warnings

---

src/components/Collapsable.jsx
src/components/ScrollToHash.jsx
src/css/custom.css
src/theme/Root.js
versioned_docs/version-2/1-click-signup/api-reference/data.mdx
versioned_docs/version-2/1-click-signup/api-reference/endpoints.mdx
versioned_docs/version-2/1-click-signup/integration-guide.mdx
versioned_docs/version-2/1-click-signup/quick-start-guide.mdx

Refactor Collapsable, fix scroll to dynamically built headers, and add collapsable to more pages
[Ticket]()
- Update Collapsable removing any animation. It instantly scrolls to oppened sections
- Adjust css to maintain font-size for headers
- Add ScrollToHash component that fixes scroll to dynamically built links using react
- Added Root component that mounts this ScrollToHash globally
- Added Collapsable sections to integration-guide to the whole page including the tabs
- Added Collapsable sections to the quick-start-guide page
- Added Collapsable sections to the data page
- Added Collapsable sections to the endpoints page

Remove transition and add integration-guide

---

versioned_docs/version-2/1-click-signup/api-reference/errors.mdx
versioned_docs/version-2/1-click-signup/integration-guide.mdx
versioned_docs/version-2/reusables/error-type.mdx
versioned_docs/version-2/reusables/when-step-is-necessary-admonition.mdx

[1-Click] errors updated to include OCE 18 & 19

[1-Click] errors updated to include OCE 18 & 19

---

versioned_docs/version-2/1-click-signup/api-reference/data.mdx

fix metadata being collapsed when it was not supposed to
[Ticket]()

fix: fix metadata being collapsed when it was not supposed to

---

versioned_docs/version-2/1-click-signup/api-reference/errors.mdx
versioned_docs/version-2/reusables/error-type.mdx

[Error Codes] OCE020 documentation added.
ref: https://github.com/VerifiedInc/core-service-v2/pull/119/checks?check_run_id=35137455191

[Error Codes] OCE020 documentation added.

---

versioned_docs/version-2/1-click-signup/api-reference/errors.mdx
versioned_docs/version-2/reusables/error-type.mdx

[Errors] removed OCE020 error code reference.
ref: https://github.com/VerifiedInc/core-service-v2/pull/121

[Errors] removed OCE020 error code reference.

---

README.md

[README] updated with latest deployment info.

[README] updated with latest deployment info.

---

src/components/DemoEmailForm.jsx
src/css/custom.css
versioned_docs/version-2/1-click-signup/api-reference/test-users.mdx
versioned_docs/version-2/1-click-signup/demo.mdx

Updated text on Demo page. Before release, need someone to make the magic demo form Collapse component expanded by default and have Lato font.
changes cherry-picked after moving default branch to `main` from this pr: https://github.com/VerifiedInc/VerifiedInc.github.io/pull/250
Basic text changes on page.
Ran locally.

[Demo] page updated

---

src/components/ErrorDisplay.jsx
versioned_docs/version-2/1-click-signup/api-reference/data.mdx
versioned_docs/version-2/1-click-signup/api-reference/errors.mdx
versioned_docs/version-2/1-click-signup/api-reference/types.mdx
versioned_docs/version-2/1-click-signup/integration-guide.mdx
versioned_docs/version-2/reusables/api-keys-admonition.mdx
versioned_docs/version-2/reusables/error-example-oce011.mdx
versioned_docs/version-2/reusables/error-example-oce017.mdx
versioned_docs/version-2/reusables/errors/ERR001.mdx
versioned_docs/version-2/reusables/errors/OCE001.mdx
versioned_docs/version-2/reusables/errors/OCE002.mdx
versioned_docs/version-2/reusables/errors/OCE003.mdx
versioned_docs/version-2/reusables/errors/OCE004.mdx
versioned_docs/version-2/reusables/errors/OCE005.mdx
versioned_docs/version-2/reusables/errors/OCE006.mdx
versioned_docs/version-2/reusables/errors/OCE007.mdx
versioned_docs/version-2/reusables/errors/OCE008.mdx
versioned_docs/version-2/reusables/errors/OCE009.mdx
versioned_docs/version-2/reusables/errors/OCE010.mdx
versioned_docs/version-2/reusables/errors/OCE011.mdx
versioned_docs/version-2/reusables/errors/OCE012.mdx
versioned_docs/version-2/reusables/errors/OCE013.mdx
versioned_docs/version-2/reusables/errors/OCE014.mdx
versioned_docs/version-2/reusables/errors/OCE015.mdx
versioned_docs/version-2/reusables/errors/OCE016.mdx
versioned_docs/version-2/reusables/errors/OCE017.mdx
versioned_docs/version-2/reusables/errors/OCE018.mdx
versioned_docs/version-2/reusables/errors/OCE019.mdx

- Updated risk signals documentation
- Added firewall errors
- Removed deprecated metadata
- Updated Gender credential
- Removed Sex credential
[Ticket]()

Updating risk signals info, adding firewall errors, removing deprecated metadata, updating Gender and removing Sex credentials

---

versioned_docs/version-2/reusables/error-type.mdx

Fixing error typo

---

docusaurus.config.js
package-lock.json
package.json
versioned_docs/version-2/1-click-signup/integration-guide.mdx
versioned_docs/version-2/reusables/errors/OCE011.mdx
versioned_docs/version-2/reusables/sequence-diagram-non-hosted.mdx
versioned_docs/version-2/reusables/sequence-diagram-semi-hosted.mdx

- Expand second step in Integration Guide by default so it's not confusing
- Update integration time estimate to be longer
- Update to stress that additionalInfo is inclusive OR
- Remove versions dropdown to hide v1
- Reorder sequence diagrams for Semi- and Non-Hosted (for clarity)
[Ticket]()

Making various small updates

---

src/components/ErrorDisplay.jsx

Fixed error display component text
- change text "messsage" to "message"

fix: error display component text

---

versioned_docs/version-2/1-click-signup/api-reference/test-users.mdx

[Test Users] typo fix

---

api/specs/api.json
src/components/Tip.jsx
versioned_docs/version-1/1-click-signup.mdx
versioned_docs/version-1/api-reference.mdx
versioned_docs/version-1/demo-1-click-signup.mdx
versioned_docs/version-1/reusables/sandbox-testing-credentials.mdx
versioned_docs/version-1/terminology.mdx
versioned_docs/version-2/1-click-signup/api-reference/data.mdx
versioned_docs/version-2/1-click-signup/api-reference/test-users.mdx
versioned_docs/version-2/reusables/1-click-entity-example.mdx
versioned_docs/version-2/reusables/errors/OCE002.mdx
versioned_docs/version-2/reusables/post-1-click-request-body-table-shared.mdx
versioned_docs/version-2/reusables/post-1-click-response-body-table-url.mdx
versioned_docs/version-2/reusables/supported-phone-numbers-admonition.mdx

[Test Users] revamped with new values. Additional Telesign test users added.
- new default user
- new telesign risk level users documented
- new oce011 users
- new no creds found user
- locally

[Test Users] revamped with new values. Additional Telesign test users added.

---

versioned_docs/version-2/1-click-signup/api-reference/test-users.mdx

[Test Users] updated to match latest mocker updates
ref: https://github.com/VerifiedInc/mock-server/pull/19
- no creds user
- telesign users
- diff addresses user
- diff birthdate user
- locally

[Test Users] updated to match latest mocker updates

---

versioned_docs/version-2.0/1-click-signup/api-reference/data.mdx
versioned_docs/version-2.1/1-click-signup/data/outputs/credentials.mdx
versioned_docs/version-2.1/1-click-signup/data/outputs/metadata.mdx

Removing Email and adding definition of risky services

---

versioned_docs/version-2.1/1-click-signup/test-users.mdx

[Test Users] typo fix pox box number
ref: https://verified-inc.slack.com/archives/C04HZMG6NBX/p1744816006988129?thread_ts=1744814760.605939&cid=C04HZMG6NBX

[Test Users] typo fix pox box number

---

versioned_docs/version-2.1/1-click-signup/guides/sdk-integration.mdx

Changing /sessionKey to /client/1-click

Fixing typos on SDK Integration guide

---

versioned_docs/version-2.0/1-click-signup/api-reference/test-users.mdx
versioned_docs/version-2.1/1-click-signup/test-users.mdx

[Test User] PO Box user removed
ref: https://github.com/VerifiedInc/Helm/pull/1391, https://verified-inc.slack.com/archives/C04HZMG6NBX/p1745348035729019?thread_ts=1745260749.551489&cid=C04HZMG6NBX

[Test User] PO Box user removed

---

versioned_docs/version-2.1/1-click-signup/sdk-reference/types.mdx

Includes the new metadata for the shared credentials and opted-out of the callback result event.
- updated types page of SDK Reference
Locally.

feat: add additional fields to SdkResult type for user credentials and opt-out cases

---

src/components/ErrorDisplay.jsx
versioned_docs/version-2.1/1-click-signup/api-reference/errors.mdx
versioned_docs/version-2.1/reusables/errors/OCE020.mdx
versioned_docs/version-2.1/reusables/errors/OCE021.mdx
versioned_docs/version-2.1/reusables/errors/SKE002.mdx

Document error codes SKE002, OCE020, and OCE021.
- chore: document SKE002 error
- chore: make data value consistent
- chore: document OCE020 and OCE021
Locally.

Document new error codes

---

versioned_docs/version-2.1/1-click-signup/guides/setup.mdx

Detailed advanced branding theme settings.
- updated guide > setup component
Locally.

docs: add advanced theme configuration option to setup guide
